<template><div class="shell">
<aside :class="{open:menuOpen}"><div class="brand"><i>K</i><div><b>Koshop</b><small>卖家工作台</small></div></div><nav><button v-for="n in nav" :class="{active:page===n.key}" @click="select(n.key)"><component :is="n.icon"/><span>{{n.name}}</span><em v-if="n.badge">{{n.badge}}</em></button></nav><footer><span></span><div><b>系统服务正常</b><small>统一工作台 · 第一阶段</small></div></footer></aside>
<main><header><button class="mobile icon" @click="menuOpen=!menuOpen"><Menu/></button><div><h1>{{title}}</h1><p>{{subtitle}}</p></div><section><time>{{today}}</time><a class="icon" :href="adminUrl" target="_blank"><ExternalLink/></a><i>管</i></section></header>
<div v-if="page==='dashboard'" class="content"><div class="welcome"><div><label>SELLER OPERATIONS</label><h2>今天也要及时处理订单和咨询</h2><p>商城经营数据、库存风险与客服接待集中在一个页面。</p></div><button class="primary" @click="load"><RefreshCw/>刷新数据</button></div><div v-if="error" class="warn"><AlertTriangle/>{{error}}<a :href="adminUrl" target="_blank">登录原后台</a></div><div class="metrics"><article v-for="m in metrics"><span :class="m.tone"><component :is="m.icon"/></span><div><small>{{m.name}}</small><b>{{m.value}}</b><em>{{m.hint}}</em></div></article></div><div class="grid"><article class="panel"><h3>近 7 日经营趋势</h3><p>订单与收入数据接入后在此展示</p><div class="chart"><i v-for="h in [40,58,48,72,64,87,75]" :style="{height:h+'%'}"></i></div></article><article class="panel"><h3>优先待办</h3><button v-for="t in todos" @click="select(t.target)"><span></span>{{t.name}}<b>{{t.value}}</b><ChevronRight/></button></article></div></div>
<div v-else-if="page==='service'" class="service"><div><span></span><section><b>客服接待工作台</b><small>咨询列表 · 当前聊天 · 买家信息</small></section><a class="primary" :href="lhcUrl" target="_blank"><ExternalLink/>新窗口打开</a></div><iframe :src="lhcUrl" title="Live Helper Chat 客服工作台"></iframe></div>
<div v-else class="content"><div class="hero"><span :class="module.tone"><component :is="module.icon"/></span><div><label>{{module.eyebrow}}</label><h2>{{module.name}}</h2><p>{{module.desc}}</p></div><a class="primary" :href="module.href" target="_blank"><ExternalLink/>进入完整管理页</a></div><article class="panel actions"><h3>快捷操作</h3><p>第一阶段通过原后台安全处理写操作，避免在浏览器中保存 API secret。</p><div><a v-for="a in module.actions" :href="a.href" target="_blank"><component :is="a.icon"/><section><b>{{a.name}}</b><small>{{a.desc}}</small></section><ChevronRight/></a></div></article><article class="panel status"><h3>集成状态</h3><p><CheckCircle2/>已提供统一导航、经营看板、客服嵌入和安全环境变量配置。</p><p><CircleDashed/>后续通过服务端代理深化商品、订单和财务写操作。</p></article></div>
</main></div></template>
<script setup lang="ts">
import {computed,onMounted,ref} from 'vue'; import {AlertTriangle,BarChart3,Box,CheckCircle2,ChevronRight,CircleDashed,ClipboardList,CreditCard,ExternalLink,Headphones,LayoutDashboard,Menu,MessageCircle,PackageCheck,RefreshCw,Settings,ShoppingBag,TriangleAlert,WalletCards} from 'lucide-vue-next';
const api=import.meta.env.VITE_DUJIAO_API_URL||'',adminUrl=import.meta.env.VITE_DUJIAO_ADMIN_URL||'https://admin.cn12.vip',lhcUrl=import.meta.env.VITE_LHC_WORKBENCH_URL||'https://kefu.cn12.vip/index.php/site_admin/chat/list'; const page=ref('dashboard'),menuOpen=ref(false),error=ref(''),data=ref<any>({}); const today=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date()); const link=(p='')=>adminUrl.replace(/\/$/,'')+'/'+p;
const nav=[{key:'dashboard',name:'工作台首页',icon:LayoutDashboard},{key:'products',name:'商品管理',icon:ShoppingBag},{key:'orders',name:'订单管理',icon:ClipboardList,badge:'待办'},{key:'finance',name:'交易 / 财务',icon:WalletCards},{key:'service',name:'客服接待',icon:Headphones,badge:'在线'},{key:'settings',name:'系统设置',icon:Settings}];
const modules:any={products:{name:'商品管理',eyebrow:'PRODUCT OPERATIONS',desc:'管理商品、上下架状态与卡密库存。',tone:'orange',icon:ShoppingBag,href:link('products'),actions:[['商品列表','查看与编辑全部商品',Box,link('products')],['新增商品','创建新的虚拟商品',ShoppingBag,link('products')],['库存预警','检查低库存商品',TriangleAlert,link()]]},orders:{name:'订单管理',eyebrow:'ORDER FULFILLMENT',desc:'查看支付与发货状态，快速处理异常订单。',tone:'blue',icon:ClipboardList,href:link('orders'),actions:[['订单列表','查看所有订单状态',ClipboardList,link('orders')],['待处理订单','处理待发货订单',PackageCheck,link('orders')],['售后处理','补发与退款入口',RefreshCw,link('orders')]]},finance:{name:'交易 / 财务',eyebrow:'PAYMENT & FINANCE',desc:'集中查看支付、钱包充值与退款记录。',tone:'green',icon:WalletCards,href:link('payments'),actions:[['支付记录','查询支付流水',CreditCard,link('payments')],['钱包充值','查看充值订单',WalletCards,link('wallet-recharges')],['经营统计','查看收入与转化',BarChart3,link()]]},settings:{name:'系统设置',eyebrow:'SYSTEM SETTINGS',desc:'快速进入站点、支付与客服配置。',tone:'purple',icon:Settings,href:link(),actions:[['站点设置','商城基础配置',Settings,link('settings')],['支付配置','管理支付渠道',CreditCard,link('payment-channels')],['客服配置','打开客服后台',MessageCircle,import.meta.env.VITE_LHC_ADMIN_URL||'https://kefu.cn12.vip/index.php/site_admin']]}}; Object.values(modules).forEach((m:any)=>m.actions=m.actions.map((a:any)=>({name:a[0],desc:a[1],icon:a[2],href:a[3]})));
const module=computed(()=>modules[page.value]||modules.products),title=computed(()=>nav.find(n=>n.key===page.value)?.name),subtitle=computed(()=>page.value==='dashboard'?'实时掌握店铺经营状态':page.value==='service'?'同时接待多个买家咨询':'统一入口，原后台安全执行'); const val=(...p:string[])=>p.reduce((v,k)=>v?.[k],data.value);
const metrics=computed(()=>[{name:'今日订单数',value:val('today','orders_total')??val('orders_total')??'—',hint:'今日创建订单',icon:ClipboardList,tone:'blue'},{name:'今日支付金额',value:val('today','paid_amount')??val('paid_amount')??'—',hint:'支付成功金额',icon:CreditCard,tone:'green'},{name:'待处理订单',value:val('orders','processing_orders')??val('processing_orders')??'—',hint:'请及时处理',icon:PackageCheck,tone:'orange'},{name:'低库存商品',value:val('products','low_stock_products')??val('low_stock_products')??'—',hint:'建议及时补充',icon:TriangleAlert,tone:'red'},{name:'当前咨询人数',value:'—',hint:'由客服系统提供',icon:MessageCircle,tone:'purple'},{name:'当前待回复',value:'—',hint:'进入客服工作台',icon:Headphones,tone:'cyan'}]); const todos=computed(()=>[{name:'待处理订单',value:metrics.value[2].value,target:'orders'},{name:'低库存商品',value:metrics.value[3].value,target:'products'},{name:'待回复咨询',value:'—',target:'service'}]); function select(k:string){page.value=k;menuOpen.value=false} async function load(){error.value='';if(!api){error.value='尚未配置 VITE_DUJIAO_API_URL，当前展示安全入口与待接入状态。';return}try{let r=await fetch(api.replace(/\/$/,'')+'/admin/dashboard/overview',{credentials:'include'});if(!r.ok)throw Error('HTTP '+r.status);let j=await r.json();data.value=j.data??j}catch(e){error.value='无法读取经营数据，请确认已登录 Admin API 并配置跨域 Cookie。'}} onMounted(load)
</script>
