server {
    listen 80;
    server_name sell.cn12.vip;
    root /var/www/koshop/apps/koshop-seller-console/dist;
    index index.html;
    location /api/koshop-seller/ {
        proxy_pass http://127.0.0.1:18100;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location / { try_files $uri $uri/ /index.html; }
}
